package main

import (
	"fmt"
)

const max = 4000000

// P002
// Each new term in the Fibonacci sequence is generated by adding the previous
// two terms. By starting with 1 and 2, the first 10 terms will be:
//
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// By considering the terms in the Fibonacci sequence whose values do not
// exceed four million, find the sum of the even-valued terms.
func main() {
	fmt.Printf("P002A: %d\n", p002A(max))
}

// フィボナッチ数列の第n項を取得する関数を定義してやる
func p002A(max int) int {
	sum := 0

	i := 2
	for f := fibA(1, 2, i); f <= max; f = fibA(1, 2, i) {
		sum += f
		i += 2
	}

	return sum
}

func fibA(a0, a1, n int) int {
	if n == 1 {
		return a0
	} else if n == 2 {
		return a1
	}

	return fibA(a0, a1, n-1) + fibA(a0, a1, n-2)
}
